// public/theme/vuejs-files/template-rtl/src/components/Estimates.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			
						<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Estimates</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link>
									</li>
									<li class="breadcrumb-item active">Estimates</li>
								</ul>
							</div>
							<div class="col-auto">
								<router-link to="/add-estimate" class="btn btn-primary me-2">
									<i class="fas fa-plus"></i>
								</router-link>
								<a class="btn btn-primary filter-btn" href="javascript:void(0);" @click="toggleContent" id="filter_search">
									<i class="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					
					<!-- Search Filter -->
					<div id="filter_inputs" class="card filter-card">
						<div class="card-body pb-0">
							<div class="row">
								<div class="col-md-3">
									<div class="form-group">
										<label>Customer:</label>
										<input type="text" class="form-control">
									</div>
								</div>
								<div class="col-md-2">
									<div class="form-group">
										<label>Status:</label>
										<select class="select">
											<option>Select Status</option>
											<option value="Draft">Draft</option>
											<option value="Sent">Sent</option>
											<option value="Viewed">Viewed</option>
											<option value="Expired">Expired</option>
											<option value="Accepted">Accepted</option>
											<option value="Rejected">Rejected</option>
										</select>
									</div>
								</div>
								<div class="col-md-2">
									<div class="form-group">
										<label>From</label>
										<div class="cal-icon">
											<input class="form-control datetimepicker" type="text">
										</div>
									</div>
								</div>
								<div class="col-md-2">
									<div class="form-group">
										<label>To</label>
										<div class="cal-icon">
											<input class="form-control datetimepicker" type="text">
										</div>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<label>Estimate Number</label>
										<input type="text" class="form-control">
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-sm-12">
							<div class="card card-table"> 
								<div class="card-body">
									
									<div class="table-responsive">
										<table class="table table-stripped table-hover datatable" id="estimatestable">
											<thead class="thead-light">
												<tr>
													<th>Estimate Number</th>
													<th>Customer</th>
													<th>Estimate Date</th>
													<th>Expiry Date</th>
													<th>Amount</th>
													<th>Status</th>
													<th class="text-end">Action</th>
												</tr>
											</thead>
											<tbody>
												<tr v-for="item in estimates" :key="item.id">
													<td><router-link to="/view-estimate">EST-17ER281</router-link></td>
													<td>
														<h2 class="table-avatar">
															<router-link to="/customer/profile"><img class="avatar avatar-sm me-2 avatar-img rounded-circle" :src="loadImg(item.customer_image)" alt="User Image"> {{item.customer_name}}</router-link>
														</h2>
													</td>
													<td>{{item.estimated_date}}</td>
													<td>{{item.expiry_date}}</td>
													<td>{{item.amount}}</td>
													<td>
                                                        <span class="badge bg-success-light" v-if="item.status == 'Accepted'">{{item.status}}</span>
                                                        <span class="badge bg-danger-light" v-if="item.status == 'Declined'">{{item.status}}</span>
                                                        <span class="badge bg-info-light" v-if="item.status == 'Sent'">{{item.status}}</span>
                                                         <span class="badge bg-warning-light" v-if="item.status == 'Expired'">{{item.status}}</span>
                                                    </td>
													<td class="text-end">
														<div class="dropdown dropdown-action">
															<a href="#" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-h"></i></a>
															<div class="dropdown-menu dropdown-menu-right">
																<router-link class="dropdown-item" to="/edit-invoice"><i class="far fa-edit me-2"></i>Edit</router-link>
																<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-trash-alt me-2"></i>Delete</a>
																<router-link class="dropdown-item" to="/view-estimate"><i class="far fa-eye me-2"></i>View</router-link>
																<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-file-alt me-2"></i>Convert to Invoice</a>
																<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-check-circle me-2"></i>Mark as sent</a>
																<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-paper-plane me-2"></i>Send Estimate</a>
																<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-check-circle me-2"></i>Mark as Accepted</a>
																<a class="dropdown-item" href="javascript:void(0);"><i class="far fa-times-circle me-2"></i>Mark as Rejected</a>
															</div>
														</div>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
							   
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->


			
		</div>
		<!-- /Main Wrapper -->
</template>
<script>
import estimates from '../assets/json/estimates.json';
const images = require.context('../assets/img/profiles', false, /\.png$|\.jpg$/)
export default {
	data() {
		return {
			estimates: estimates
		}
	},
	mounted() {
		// Datetimepicker
	
	if($('.datetimepicker').length > 0 ){
		$('.datetimepicker').datetimepicker({
			format: 'DD-MM-YYYY',
			icons: {
				up: "fas fa-angle-up",
				down: "fas fa-angle-down",
				next: 'fas fa-angle-right',
				previous: 'fas fa-angle-left'
			}
		});
	}
        if ($('.select').length > 0) {
            $('.select').select2({
                minimumResultsForSearch: -1,
                width: '100%'
            });
		}
		if ($('.datatable').length > 0) {
		$('.datatable').DataTable({
			"bFilter": false,
		});
	}
	$(document).on('click', '#filter_search', function() {
		$('#filter_inputs').slideToggle("slow");
	});
		
	},
	methods: {
        loadImg(imgPath) {
            return images('./' + imgPath).default
		},
		toggleContent() {
			this.toggleCheck = !this.toggleCheck;
		}
        
    },
}
</script>

// public/theme/reactjs-files/template-rtl/src/estimates/Index.jsx
import React, {useState, useEffect} from 'react'
import { Link } from 'react-router-dom'
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import estimates from '../json/estimates'
import datatable from '../utils/utils'
import Select2 from 'react-select2-wrapper';
import DatePicker from 'react-datepicker';

const Estimates = () => {
    const [date, setDate] = useState(new Date());
	const [options, setOptions] = useState([
		{ id: 1, text: 'Draft' },
		{ id: 2, text: 'Sent' },
		{ id: 3, text: 'Viewed' },
		{ id: 4, text: 'Expired' },
		{ id: 5, text: 'Accepted' },
		{ id: 6, text: 'Rejected' },
	]);
	
	useEffect(() => {
		datatable('#estimatestable')
		$("#filter_search").click(function(){
			$("#filter_inputs").slideToggle(500);
        });
        let elements = Array.from(document.getElementsByClassName('select2-container'));
        elements.map(element => element.classList.add("width-100"))
	},[]);

    const handleChange = (date) => {
        setDate(date)
    }
    
        return (
		<div className="main-wrapper">
            <Header />
			<Sidebar />
			
			<div className="page-wrapper">
				<div className="content container-fluid">
					<div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Estimates</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
									</li>
									<li className="breadcrumb-item active">Estimates</li>
								</ul>
							</div>
							<div className="col-auto">
								<Link to="/add-estimate" className="btn btn-primary me-1">
									<i className="fas fa-plus"></i>
								</Link>
								<a className="btn btn-primary filter-btn" href="/estimates#" id="filter_search">
									<i className="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					
					<div id="filter_inputs" className="card filter-card">
						<div className="card-body pb-0">
							<div className="row">
								<div className="col-md-3">
									<div className="form-group">
										<label>Customer:</label>
										<input type="text" className="form-control" />
									</div>
								</div>
								<div className="col-md-2">
									<div className="form-group">
										<label>Status:</label>
                                        <Select2
                                            className="w-100"
                                            data={options}
                                            options={{
                                                placeholder: 'Select Status',
                                            }}
                                        />
									</div>
								</div>
								<div className="col-md-2">
									<div className="form-group">
										<label>From</label>
										<div className="cal-icon">
                                            <DatePicker
                                                selected={date}
                                                onChange={handleChange}
                                                className="form-control datetimepicker"
                                            />
										</div>
									</div>
								</div>
								<div className="col-md-2">
									<div className="form-group">
										<label>To</label>
										<div className="cal-icon">
                                            <DatePicker
                                                selected={date}
                                                onChange={handleChange}
                                                className="form-control datetimepicker"
                                            />
										</div>
									</div>
								</div>
								<div className="col-md-3">
									<div className="form-group">
										<label>Estimate Number</label>
										<input type="text" className="form-control" />
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div className="row">
						<div className="col-sm-12">
							<div className="card card-table"> 
								<div className="card-body">
									
									<div className="table-responsive">
										<table className="table table-stripped table-hover datatable" id="estimatestable">
											<thead className="thead-light">
												<tr>
													<th>Estimate Number</th>
													<th>Customer</th>
													<th>Estimate Date</th>
													<th>Expiry Date</th>
													<th>Amount</th>
													<th>Status</th>
													<th className="text-right">Action</th>
												</tr>
											</thead>
											<tbody>
                                            {estimates.map((item, index) => {
                                                    let status;
                                                    if(item.status === 'Accepted') {
                                                        status = <span className="badge badge-pill bg-success-light">{item.status}</span>
                                                    } else if(item.status === 'Declined') {
                                                        status = <span className="badge badge-pill bg-danger-light">{item.status}</span>
                                                    } else {
                                                        status = <span className="badge badge-pill bg-info-light">{item.status}</span>
                                                    } 
                                                    return (
												<tr key={index}>
													<td><Link to="/view-estimate">{item.estimate_number}</Link></td>
													<td>
														<h2 className="table-avatar">
															<Link to="/profile"><img className="avatar avatar-sm me-2 avatar-img rounded-circle" src={item.customer_image} alt="User Image" />{item.customer_name}</Link>
														</h2>
													</td>
													<td>{item.estimated_date}</td>
													<td>{item.expiry_date}</td>
													<td>{item.amount}</td>
													<td>{status}</td>
													<td className="text-right">
														<div className="dropdown dropdown-action">
															<a href="#" className="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
																<i className="fas fa-ellipsis-h" />
															</a>
															<div className="dropdown-menu dropdown-menu-right">
																<Link className="dropdown-item" to="/edit-invoice"><i className="far fa-edit me-2"></i>Edit</Link>
																<a className="dropdown-item" href="#"><i className="far fa-trash-alt me-2"></i>Delete</a>
																<Link className="dropdown-item" to="/view-estimate"><i className="far fa-eye me-2"></i>View</Link>
																<a className="dropdown-item" href="#"><i className="far fa-file-alt me-2"></i>Convert to Invoice</a>
																<a className="dropdown-item" href="#"><i className="far fa-check-circle me-2"></i>Mark as sent</a>
																<a className="dropdown-item" href="#"><i className="far fa-paper-plane me-2"></i>Send Estimate</a>
																<a className="dropdown-item" href="#"><i className="far fa-check-circle me-2"></i>Mark as Accepted</a>
																<a className="dropdown-item" href="#"><i className="far fa-times-circle me-2"></i>Mark as Rejected</a>
															</div>
														</div>
													</td>
												</tr>
												);  })}
											</tbody>
										</table>
									</div>
							   
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
        );
}
export default Estimates;
