// public/theme/vuejs-files/template/src/components/TaxTypes.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col-sm-6">
								<h3 class="page-title">Settings</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link>
									</li>
									<li class="breadcrumb-item active">Tax Types</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
				
					<div class="row">
						<div class="col-xl-3 col-md-4">
                            <layout-settings-sidebar></layout-settings-sidebar>
						</div>
						
						<div class="col-xl-9 col-md-8">
							<div class="card card-table">
								<div class="card-header">
									<div class="row">
										<div class="col">
											<h5 class="card-title">Tax Types</h5>
										</div>
										<div class="col-auto">
											<a href="javascript:void(0);" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#add_tax">Add New Tax</a>
										</div>
									</div>
								</div>
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-hover mb-0">
											<thead class="thead-light">
												<tr>
													<th>Tax Name </th>
													<th>Tax Percentage (%) </th>
													<th>Status</th>
													<th class="text-right">Action</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>VAT</td>
													<td>14%</td>
													<td>
														<span class="badge bg-success-light">Active</span>
													</td>
													<td class="text-right">
														<a href="#" data-bs-toggle="modal" data-bs-target="#edit_tax" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-1"></i> Edit</a> 
														<a href="#" data-bs-toggle="modal" data-bs-target="#delete_tax" class="btn btn-sm btn-white text-danger me-2"><i class="far fa-trash-alt me-1"></i>Delete</a>
													</td>
												</tr>
												<tr>
													<td>GST</td>
													<td>30%</td>
													<td>
														<span class="badge bg-danger-light">Inactive</span>
													</td>
													<td class="text-right">
														<a href="#" data-bs-toggle="modal" data-bs-target="#edit_tax" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-1"></i> Edit</a> 
														<a href="#" data-bs-toggle="modal" data-bs-target="#delete_tax" class="btn btn-sm btn-white text-danger me-2"><i class="far fa-trash-alt me-1"></i>Delete</a>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<!-- Add Tax Modal -->
					<div id="add_tax" class="modal custom-modal fade" role="dialog">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">Add Tax</h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
								</div>
								<div class="modal-body">
									<form>
										<div class="form-group">
											<label>Tax Name <span class="text-danger">*</span></label>
											<input class="form-control" type="text">
										</div>
										<div class="form-group">
											<label>Tax Percentage (%) <span class="text-danger">*</span></label>
											<input class="form-control" type="text">
										</div>
										<div class="form-group">
											<label>Status <span class="text-danger">*</span></label>
											<select class="select">
												<option>Pending</option>
												<option>Approved</option>
											</select>
										</div>
										<div class="submit-section">
											<button class="btn btn-primary submit-btn">Submit</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- /Add Tax Modal -->
					
					<!-- Edit Tax Modal -->
					<div id="edit_tax" class="modal custom-modal fade" role="dialog">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title">Edit Tax</h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
								</div>
								<div class="modal-body">
									<form>
										<div class="form-group">
											<label>Tax Name <span class="text-danger">*</span></label>
											<input class="form-control" value="VAT" type="text">
										</div>
										<div class="form-group">
											<label>Tax Percentage (%)  <span class="text-danger">*</span></label>
											<input class="form-control" value="14%" type="text">
										</div>
										<div class="form-group">
											<label>Status <span class="text-danger">*</span></label>
											<select class="select">
												<option>Active</option>
												<option>Inactive</option>
											</select>
										</div>
										<div class="submit-section">
											<button class="btn btn-primary submit-btn">Save</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<!-- /Edit Tax Modal -->
					
					<!-- Delete Tax Modal -->
					<div class="modal custom-modal fade" id="delete_tax" role="dialog">
						<div class="modal-dialog modal-dialog-centered">
							<div class="modal-content">
								<div class="modal-body">
									<div class="modal-icon text-center mb-3">
										<i class="fas fa-trash-alt text-danger"></i>
									</div>
									<div class="modal-text text-center">
										<h2>Delete Tax</h2>
										<p>Are you sure want to delete?</p>
									</div>
								</div>
								<div class="modal-footer text-center">
									<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
									<button type="button" class="btn btn-primary">Delete</button>
								</div>
							</div>
						</div>
					</div>
					<!-- /Delete Tax Modal -->
					
				</div>
			</div>
			<!-- /Page Wrapper -->
			
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
export default {
	mounted() {
        if ($('.select').length > 0) {
            $('.select').select2({
                minimumResultsForSearch: -1,
                width: '100%'
            });
        }
	},
}
</script>

// public/theme/reactjs-files/template-rtl/src/settings/TaxTypes.jsx
import React, {useState, useEffect} from 'react';
import { Link } from 'react-router-dom';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import SettingSidebar from '../layouts/SettingsSidebar'
import Select2 from 'react-select2-wrapper';

const TaxTypes = () => {
   
	const [status, setstatus ] = useState( [
        { id: 1, text: 'Active' },
        { id: 2, text: 'Inactive' },
    	]);


    const formHandler = (e) => {
        console.log(e);
    }

    useEffect(() => {
		let elements = Array.from(document.getElementsByClassName('select2-container'));
        elements.map(element => element.classList.add("width-100"))
	},[]);

        return (

            <div className="main-wrapper">
            
               <Header />
                <Sidebar />
                
                <div className="page-wrapper">
                    <div className="content container-fluid">
                    
                        <div className="page-header">
                            <div className="row">
                                <div className="col-sm-6">
                                    <h3 className="page-title">Settings</h3>
                                    <ul className="breadcrumb">
                                        <li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
                                        </li>
                                        <li className="breadcrumb-item active">Tax Types</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    
                        <div className="row">
                            <div className="col-xl-3 col-md-4">
                                <SettingSidebar />
                            </div>
                            
                            <div className="col-xl-9 col-md-8">
                                <div className="card card-table">
                                    <div className="card-header">
                                        <div className="row">
                                            <div className="col">
                                                <h5 className="card-title">Tax Types</h5>
                                            </div>
                                            <div className="col-auto">
                                                <a href="#" className="btn btn-outline-primary btn-sm" data-toggle="modal" data-target="#add_tax">Add New Tax</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="card-body">
                                        <div className="table-responsive">
                                            <table className="table table-hover mb-0">
                                                <thead className="thead-light">
                                                    <tr>
                                                        <th>Tax Name </th>
                                                        <th>Tax Percentage (%) </th>
                                                        <th>Status</th>
                                                        <th className="text-right">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td>VAT</td>
                                                        <td>14%</td>
                                                        <td>
                                                            <span className="badge bg-success-light">Active</span>
                                                        </td>
                                                        <td className="text-right">
                                                            <a href="#" data-toggle="modal" data-target="#edit_tax" className="btn btn-sm btn-white text-success me-2"><i className="far fa-edit me-1"></i> Edit</a> 
                                                            <a href="#" data-toggle="modal" data-target="#delete_tax" className="btn btn-sm btn-white text-danger me-2"><i className="far fa-trash-alt me-1"></i>Delete</a>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td>GST</td>
                                                        <td>30%</td>
                                                        <td>
                                                            <span className="badge bg-danger-light">Inactive</span>
                                                        </td>
                                                        <td className="text-right">
                                                            <a href="#" data-toggle="modal" data-target="#edit_tax" className="btn btn-sm btn-white text-success me-2"><i className="far fa-edit me-1"></i> Edit</a> 
                                                            <a href="#" data-toggle="modal" data-target="#delete_tax" className="btn btn-sm btn-white text-danger me-2"><i className="far fa-trash-alt me-1"></i>Delete</a>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div id="add_tax" className="modal custom-modal fade" role="dialog">
                            <div className="modal-dialog modal-dialog-centered" role="document">
                                <div className="modal-content">
                                    <div className="modal-header">
                                        <h5 className="modal-title">Add Tax</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div className="modal-body">
                                        <form>
                                            <div className="form-group">
                                                <label>Tax Name <span className="text-danger">*</span></label>
                                                <input className="form-control" type="text"  onChange={formHandler}/>
                                            </div>
                                            <div className="form-group">
                                                <label>Tax Percentage (%) <span className="text-danger">*</span></label>
                                                <input className="form-control" type="text" onChange={formHandler} />
                                            </div>
                                            <div className="form-group">
                                                <label>Status <span className="text-danger">*</span></label>
                                                <Select2
                                                    defaultValue={1}
                                                    className="w-100"
                                                    data={status}
                                                    options={{
                                                        placeholder: 'Select Status',
                                                    }}
                                                />
                                            </div>
                                            <div className="submit-section">
                                                <button className="btn btn-primary submit-btn">Submit</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div id="edit_tax" className="modal custom-modal fade" role="dialog">
                            <div className="modal-dialog modal-dialog-centered" role="document">
                                <div className="modal-content">
                                    <div className="modal-header">
                                        <h5 className="modal-title">Edit Tax</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div className="modal-body">
                                        <form>
                                            <div className="form-group">
                                                <label>Tax Name <span className="text-danger">*</span></label>
                                                <input className="form-control" value="VAT" type="text" onChange={formHandler} />
                                            </div>
                                            <div className="form-group">
                                                <label>Tax Percentage (%)  <span className="text-danger">*</span></label>
                                                <input className="form-control" value="14%" type="text" onChange={formHandler} />
                                            </div>
                                            <div className="form-group">
                                                <label>Status <span className="text-danger">*</span></label>
                                                <Select2
                                                    defaultValue={1}
                                                    className="w-100 select"
                                                    data={status}
                                                    options={{
                                                        placeholder: 'Select Status',
                                                    }}
                                                />
                                            </div>
                                            <div className="submit-section">
                                                <button className="btn btn-primary submit-btn">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div className="modal custom-modal fade" id="delete_tax" role="dialog">
                            <div className="modal-dialog modal-dialog-centered">
                                <div className="modal-content">
                                    <div className="modal-body">
                                        <div className="modal-icon text-center mb-3">
                                            <i className="fas fa-trash-alt text-danger"></i>
                                        </div>
                                        <div className="modal-text text-center">
                                            <h2>Delete Tax</h2>
                                            <p>Are you sure want to delete?</p>
                                        </div>
                                    </div>
                                    <div className="modal-footer text-center">
                                        <button type="button" className="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                        <button type="button" className="btn btn-primary">Delete</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
            </div>
        );
    
}
export default TaxTypes;
