// public/theme/reactjs-files/template/src/customers/Index.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom';
import customers from '../json/customers';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import $ from 'jquery'
const SlideToggle = window.ReactSlideToggle

const Customers = () => {

	useEffect(() => {
        $('#customerstable').DataTable({
			"bFilter": false,
			"paging": true,
		});
		$("#filter_search").click(function(){
			$("#filter_inputs").slideToggle(500);
		});
	},[]);
	
    return (
		<div className="main-wrapper">
		
			<Header />
			<Sidebar />
			
			<div className="page-wrapper">
				<div className="content container-fluid">
				
					<div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Customers</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
									</li>
									<li className="breadcrumb-item active">Customers</li>
								</ul>
							</div>
							<div className="col-auto">
								<Link to="/add-customer" className="btn btn-primary mr-1">
									<i className="fas fa-plus"></i>
								</Link>
								<a className="btn btn-primary filter-btn" href="/customers#" id="filter_search">
									<i className="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					<div id="filter_inputs" className="card filter-card">
						<div className="card-body pb-0">
							<div className="row">
								<div className="col-sm-6 col-md-3">
									<div className="form-group">
										<label>Name</label>
										<input type="text" className="form-control" />
									</div>
								</div>
								<div className="col-sm-6 col-md-3">
									<div className="form-group">
										<label>Email</label>
										<input type="text" className="form-control" />
									</div>
								</div>
								<div className="col-sm-6 col-md-3">
									<div className="form-group">
										<label>Phone</label>
										<input type="text" className="form-control" />
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div className="row">
						<div className="col-sm-12">
							<div className="card card-table">
								<div className="card-body">
									<div className="table-responsive">
										<table className="table table-center table-hover datatable" id="customerstable">
											<thead className="thead-light">
												<tr>
													<th>Customer</th>
													<th>Email</th>
													<th>Amount Due</th>
													<th>Registered On</th>
													<th>Status</th>
													<th className="text-right">Actions</th>
												</tr>
											</thead>
											<tbody>
											{customers.map((item, index) => {
												let status;
												if(item.status === 'Active') {
													status = <span className="badge badge-pill bg-success-light">Active</span>
												} else {
													status = <span className="badge badge-pill bg-danger-light">Inactive</span>
												}
												return (
												<tr key={index}>
													<td>
														<h2 className="table-avatar">
															<Link to="/profile" className="avatar avatar-sm mr-2"><img className="avatar-img rounded-circle" src={item.customer_image} alt="User Image" /></Link>
															<Link to="/profile">{item.customer_name}<span>{item.customer_mobile}</span></Link>
														</h2>
													</td>
													<td>{item.customer_email}</td>
													<td>{item.amount_due}</td>
													<td>{item.registered_on}</td>
													<td>{status}</td>
													<td className="text-right">
														<Link to="/edit-customer" className="btn btn-sm btn-white text-success mr-2"><i className="far fa-edit mr-1"></i> Edit</Link> 
														<a href="#" className="btn btn-sm btn-white text-danger mr-2"><i className="far fa-trash-alt mr-1"></i>Delete</a>
													</td>
												</tr>
											 );  })}
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
        );
}
export default Customers;

// public/theme/vuejs-files/template/src/components/Customers.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
			<layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Customers</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link>
									</li>
									<li class="breadcrumb-item active">Customers</li>
								</ul>
							</div>
							<div class="col-auto">
								<router-link to="/add-customer" class="btn btn-primary me-2">
									<i class="fas fa-plus"></i>
								</router-link>
								<a class="btn btn-primary filter-btn" href="javascript:void(0);" id="filter_search">
									<i class="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
						
						<!-- Search Filter -->
					<div id="filter_inputs" class="card filter-card">
						<div class="card-body pb-0">
							<div class="row">
								<div class="col-sm-6 col-md-3">
									<div class="form-group">
										<label>Name</label>
										<input type="text" class="form-control">
									</div>
								</div>
								<div class="col-sm-6 col-md-3">
									<div class="form-group">
										<label>Email</label>
										<input type="text" class="form-control">
									</div>
								</div>
								<div class="col-sm-6 col-md-3">
									<div class="form-group">
										<label>Phone</label>
										<input type="text" class="form-control">
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-sm-12">
							
							<div class="card card-table">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center table-hover datatable" id="customerTable">
											<thead class="thead-light">
												<tr>
													<th>Customer</th>
													<th>Email</th>
													<th>Amount Due</th>
													<th>Registered On</th>
													<th>Status</th>
													<th class="text-right">Actions</th>
												</tr>
											</thead>
											<tbody>
												<tr v-for="item in customers" :key="item.id">
													<td>
														<h2 class="table-avatar">
															<router-link to="/customer/profile" class="avatar avatar-sm me-2"><img class="avatar-img rounded-circle" :src="loadImg(item.customer_image)" alt="User Image"></router-link>
															<router-link to="/customer/profile">{{item.customer_name}} <span>{{item.customer_mobile}}</span></router-link>
														</h2>
													</td>
													<td>{{item.customer_email}}</td>
													<td>{{item.amount_due}}</td>
													<td>{{item.registered_on}}</td>
													<td>
														<span class="badge badge-pill bg-success-light" v-if="item.status == 'Active'">Active</span>
														<span class="badge badge-pill bg-danger-light" v-if="item.status == 'Inactive'">Inactive</span>
													</td>
													<td class="text-right">
														<router-link to="/edit-customer" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-2"></i> Edit</router-link> 
														<a href="javascript:void(0);" class="btn btn-sm btn-white text-danger me-2"><i class="far fa-trash-alt me-2"></i>Delete</a>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
			
		</div>
		<!-- /Main Wrapper -->
</template>
<script>
import customers from '../assets/json/customers.json';
const images = require.context('../assets/img/profiles', false, /\.png$|\.jpg$/)
export default {
	data() {
		return {
			customers: customers
		}
	},
	mounted() {
		if ($('.datatable').length > 0) {
		$('.datatable').DataTable({
			"bFilter": false,
		});
	}
	$(document).on('click', '#filter_search', function() {
		$('#filter_inputs').slideToggle("slow");
	});
	},
	methods: {
        loadImg(imgPath) {
            return images('./' + imgPath).default
		}
    },
}
</script>
