// public/theme/reactjs-files/template/src/customers/EditCustomer.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import Select2 from 'react-select2-wrapper';

const EditCustomer = () => {

    const [date, setDate] = useState(new Date());
	const [currencyOptions, setcurrencyOptions] = useState([
        { id: 1, text: 'Select Currency' },
        { id: 2, text: 'EUR Euro' },
        { id: 3, text: 'INR Indoan Rupee' },
        { id: 4, text: 'USD- US Dollar' }
    ]);
    const [countryOptions, setcountryOptions] = useState([
        {  id: 1, text: 'Select Country' },
        {  id: 2, text: 'Afghanistan' },
        {  id: 3, text: 'Albania' },
        {  id: 4, text: 'American Samoa' },
        {  id: 5, text: 'Algeria' },
        {  id: 6, text: 'Andorra' },
        {  id: 7, text: 'Angola' },
        {  id: 8, text: 'Anguilla' },
        {  id: 9, text: 'United States' }
    ]);

    const [currency, setCurrency] = useState("")

    const formHandler = (e) => {
        console.log(e)
    }

    const handleChange = selectedCurrency => {
        setCurrency(selectedCurrency)
    };
    
        return (

            <div className="main-wrapper">
                <Header />
                <Sidebar />
                
                <div className="page-wrapper">
                    <div className="content container-fluid">
                    
                        <div className="page-header">
                            <div className="row">
                                <div className="col-sm-12">
                                    <h3 className="page-title">Customers</h3>
                                    <ul className="breadcrumb">
                                        <li className="breadcrumb-item"><Link to="/index">Dashboard</Link></li>
                                        <li className="breadcrumb-item"><Link to="/customers">Customers</Link></li>
                                        <li className="breadcrumb-item active">Edit Customers</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                        <div className="row">
                            <div className="col-md-12">
                                <div className="card">
                                    <div className="card-body">
                                        <h4 className="card-title">Basic Info</h4>
                                        <form>
                                            <div className="row">
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Display Name</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="Brian Johnson" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Email</label>
                                                        <input type="email" className="form-control" onChange={formHandler} value="brianjohnson@example.com" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Primary Currency</label>
                                                        <Select2
                                                            defaultValue={2} className="w-100"
                                                            data={currencyOptions}
                                                            options={{
                                                                placeholder: 'Currency',
                                                            }}
                                                            />
                                                    </div>
                                                </div>
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Primary Contact Name</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="Brian Johnson" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Phone</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="+1-252-444-7535" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Website</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="http://www.example.com" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <h4 className="card-title mt-4">Billing Address</h4>
                                        <form >
                                            <div className="row">
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Name</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="Brian Johnson" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>State</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="Georgia" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Address</label>
                                                        <textarea rows="5" cols="5" className="form-control" onChange={formHandler} placeholder="938 Green Acres Road"></textarea>
                                                    </div>
                                                </div>
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Country</label>
                                                        <Select2
                                                            defaultValue={2} className="w-100"
                                                            data={countryOptions}
                                                            options={{
                                                                placeholder: 'Country',
                                                            }}
                                                        />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>City</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="ROME" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Phone</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="+1-252-444-7535" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Zip Code</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="30161" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <h4 className="card-title mt-4">Shipping Address</h4>
                                        <form>
                                            <div className="text-right">
                                                <button type="submit" className="btn btn-outline-primary btn-sm">Copy from Billing</button>
                                            </div>
                                            <div className="row">
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Name</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="Brian Johnson" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>State</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="Georgia" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Address</label>
                                                        <textarea rows="5" cols="5" className="form-control" onChange={formHandler} placeholder="938 Green Acres Road"></textarea>
                                                    </div>
                                                </div>
                                                <div className="col-md-6">
                                                    <div className="form-group">
                                                        <label>Country</label>
                                                        <Select2
                                                            defaultValue={2} className="w-100"
                                                            data={countryOptions}
                                                            options={{
                                                                placeholder: 'Country',
                                                            }}
                                                        />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>City</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="ROME" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Phone</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="+1-252-444-7535" />
                                                    </div>
                                                    <div className="form-group">
                                                        <label>Zip Code:</label>
                                                        <input type="text" className="form-control" onChange={formHandler} value="30161" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="text-right mt-4">
                                                <button type="submit" className="btn btn-primary">Save Changes</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
}
export default EditCustomer;

// public/theme/vuejs-files/template/src/components/EditCustomer.vue
<template>
    	<!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col-sm-12">
								<h3 class="page-title">Customers</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link></li>
									<li class="breadcrumb-item"><router-link to="/customers">Customers</router-link></li>
									<li class="breadcrumb-item active">Edit Customers</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-body">
									<h4 class="card-title">Basic Info</h4>
									<form action="#">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label>Display Name</label>
													<input type="text" class="form-control" value="Brian Johnson">
												</div>
												<div class="form-group">
													<label>Email</label>
													<input type="email" class="form-control" value="brianjohnson@example.com">
												</div>
												<div class="form-group">
													<label>Primary Currency</label>
													<select class="select">
														<option selected>USD- US Dollar</option>
														<option>EUR Euro</option>
														<option>INR Indoan Rupee</option>
													</select>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>Primary Contact Name</label>
													<input type="text" class="form-control" value="Brian Johnson">
												</div>
												<div class="form-group">
													<label>Phone</label>
													<input type="text" class="form-control" value="+1-252-444-7535">
												</div>
												<div class="form-group">
													<label>Website</label>
													<input type="text" class="form-control" value="http://www.example.com">
												</div>
											</div>
										</div>
									</form>
									<h4 class="card-title mt-4">Billing Address</h4>
									<form action="#">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label>Name</label>
													<input type="text" class="form-control" value="Brian Johnson">
												</div>
												<div class="form-group">
													<label>State</label>
													<input type="text" class="form-control" value="Georgia">
												</div>
												<div class="form-group">
													<label>Address</label>
													<textarea rows="5" cols="5" class="form-control" placeholder="938 Green Acres Road"></textarea>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>Country</label>
													<select class="select">
														<option>Afghanistan</option>
														<option>Afghanistan</option>
														<option>Albania</option>
														<option>Algeria</option>
														<option>American Samoa</option>
														<option>Andorra</option>
														<option>Angola</option>
														<option>Anguilla</option>
														<option selected>United States</option>
													</select>
												</div>
												<div class="form-group">
													<label>City</label>
													<input type="text" class="form-control" value="ROME">
												</div>
												<div class="form-group">
													<label>Phone</label>
													<input type="text" class="form-control" value="+1-252-444-7535">
												</div>
												<div class="form-group">
													<label>Zip Code</label>
													<input type="text" class="form-control" value="30161">
												</div>
											</div>
										</div>
									</form>
									<h4 class="card-title mt-4">Shipping Address</h4>
									<form action="#">
										<div class="text-end">
											<button type="submit" class="btn btn-outline-primary btn-sm">Copy from Billing</button>
										</div>
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<label>Name</label>
													<input type="text" class="form-control" value="Brian Johnson">
												</div>
												<div class="form-group">
													<label>State</label>
													<input type="text" class="form-control" value="Georgia">
												</div>
												<div class="form-group">
													<label>Address</label>
													<textarea rows="5" cols="5" class="form-control" placeholder="938 Green Acres Road"></textarea>
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<label>Country</label>
													<select class="select">
														<option>Afghanistan</option>
														<option>Afghanistan</option>
														<option>Albania</option>
														<option>Algeria</option>
														<option>American Samoa</option>
														<option>Andorra</option>
														<option>Angola</option>
														<option>Anguilla</option>
														<option selected>United States</option>
													</select>
												</div>
												<div class="form-group">
													<label>City</label>
													<input type="text" class="form-control" value="ROME">
												</div>
												<div class="form-group">
													<label>Phone</label>
													<input type="text" class="form-control" value="+1-252-444-7535">
												</div>
												<div class="form-group">
													<label>Zip Code:</label>
													<input type="text" class="form-control" value="30161">
												</div>
											</div>
										</div>
										<div class="text-end mt-4">
											<button type="submit" class="btn btn-primary">Save Changes</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
			
		</div>
		<!-- /Main Wrapper -->
</template>

<script>
export default {
    mounted() {
            // Select 2
        if ($('.select').length > 0) {
            $('.select').select2({
                minimumResultsForSearch: -1,
                width: '100%'
            });
        }
    }
}
</script>
