// public/theme/vuejs-files/template-rtl/src/components/Expenses.vue
<template>
    	<!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Expenses</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link></li>
									<li class="breadcrumb-item active">Expenses</li>
								</ul>
							</div>
							<div class="col-auto">
								<router-link to="/add-expense"  class="btn btn-primary me-1">
									<i class="fas fa-plus"></i>
								</router-link>
								<a class="btn btn-primary filter-btn" href="javascript:void(0);" @click="toggleContent" id="filter_search">
									<i class="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
			   
					<!-- Search Filter -->
					<div id="filter_inputs" class="card filter-card">
						<div class="card-body pb-0">
							<div class="row">
								<div class="col-md-3">
									<div class="form-group">
										<label>Customer:</label>
										<input type="text" class="form-control">
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<label>Category:</label>
										<select class="select">
											<option>Select Category</option>
											<option>Advertising</option>
											<option>Marketing</option>
											<option>Software</option>
											<option>Travel</option>
										</select>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<label>From</label>
										<div class="cal-icon">
											<input class="form-control datetimepicker" type="text">
										</div>
									</div>
								</div>
								<div class="col-md-3">
									<div class="form-group">
										<label>To</label>
										<div class="cal-icon">
											<input class="form-control datetimepicker" type="text">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-sm-12">
							<div class="card card-table"> 
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center table-hover datatable" id="expensesTable">
											<thead class="thead-light">
												<tr>
													<th>Category</th>
													<th>Customer</th>
													<th>Expense Date</th>
													<th>Notes</th>
													<th>Amount</th>
													<th>Status</th>
													<th class="text-end">Action</th>
												</tr>
											</thead>
											<tbody>
												<tr v-for="item in expenses" :key="item.id">
													<td>{{item.category}}</td>
													<td>
														<h2 class="table-avatar">
															<router-link to="/customer/profile"><img class="avatar avatar-sm me-2 avatar-img rounded-circle" :src="loadImg(item.customer_image)" alt="User Image"> {{item.customer_name}}</router-link>
														</h2>
													</td>
													<td>{{item.expense_date}}</td>
													<td>{{item.notes}}</td>
													<td>{{item.amount}}</td>
													<td>
                                                        <span class="badge badge-pill bg-success-light" v-if="item.status == 'Approved'">Approved</span>
                                                        <span class="badge badge-pill bg-danger-light" v-if="item.status == 'Pending'">Pending</span>
                                                    </td>
													<td class="text-end">
														<router-link to="/edit-expense" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-1"></i> Edit</router-link> 
														<a href="javascript:void(0);" class="btn btn-sm btn-white text-danger"><i class="far fa-trash-alt me-1"></i>Delete</a>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
			
		</div>
		<!-- /Main Wrapper -->
</template>
<script>
import expenses from '../assets/json/expenses.json';
const images = require.context('../assets/img/profiles', false, /\.png$|\.jpg$/)
export default {
	data() {
		return {
			expenses: expenses
		}
	},
	mounted() {
			// Datetimepicker
	
	if($('.datetimepicker').length > 0 ){
		$('.datetimepicker').datetimepicker({
			format: 'DD-MM-YYYY',
			icons: {
				up: "fas fa-angle-up",
				down: "fas fa-angle-down",
				next: 'fas fa-angle-right',
				previous: 'fas fa-angle-left'
			}
		});
	}
	if ($('.datatable').length > 0) {
		$('.datatable').DataTable({
			"bFilter": false,
		});
	}

		
        
        if ($('.select').length > 0) {
            $('.select').select2({
                minimumResultsForSearch: -1,
                width: '100%'
            });
        }
        $(document).on('click', '#filter_search', function() {
			$('#filter_inputs').slideToggle("slow");
		});
	},
	methods: {
        loadImg(imgPath) {
            return images('./' + imgPath).default
        }
    },
}
</script>

// public/theme/reactjs-files/template-rtl/src/expenses/Index.jsx
import React, {useState, useEffect} from 'react'
import { Link } from 'react-router-dom'
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import expenses from '../json/expenses'
import datatable from '../utils/utils'
import Select2 from 'react-select2-wrapper';
import DatePicker from 'react-datepicker';

const Expenses = () => {
    
    const [date, setDate] = useState(new Date());
	const [categoryOptions, setCategoryOptions] = useState([
        { id: 1, text: 'Advertising' },
        { id: 2, text: 'Marketing' },
        { id: 3, text: 'Software' },
        { id: 4, text: 'Travel' }
	]);

    useEffect(() => {
        datatable('#expensestable')
		$("#filter_search").click(function(){
			$("#filter_inputs").slideToggle(500);
        });
        let elements = Array.from(document.getElementsByClassName('select2-container'));
        elements.map(element => element.classList.add("width-100"))
	},[]);

    const handleChange = (date) => {
        setDate(date)
    }

        return (

            <div className="main-wrapper">
                <Header />
                <Sidebar />
                
                <div className="page-wrapper">
                    <div className="content container-fluid">
                    
                    <div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Expenses</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link></li>
									<li className="breadcrumb-item active">Expenses</li>
								</ul>
							</div>
							<div className="col-auto">
								<Link to="/add-expenses"  className="btn btn-primary m-1">
									<i className="fas fa-plus"></i>
								</Link>
								<a className="btn btn-primary filter-btn" href="/expenses#" id="filter_search">
									<i className="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
                   
                        <div id="filter_inputs" className="card filter-card">
                            <div className="card-body pb-0">
                                <div className="row">
                                    <div className="col-md-3">
                                        <div className="form-group">
                                            <label>Customer:</label>
                                            <input type="text" className="form-control" />
                                        </div>
                                    </div>
                                    <div className="col-md-3">
                                        <div className="form-group">
                                            <label>Category:</label>
                                            <Select2
                                               className="w-100"
                                                data={categoryOptions}
                                                options={{
                                                    placeholder: 'Select Category',
                                                }}
                                            />
                                        </div>
                                    </div>
                                    <div className="col-md-3">
                                        <div className="form-group">
                                            <label>From</label>
                                            <div className="cal-icon">
                                            <DatePicker
                                                selected={date}
                                                onChange={handleChange}
                                                className="form-control datetimepicker"
                                            />
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-md-3">
                                        <div className="form-group">
                                            <label>To</label>
                                            <div className="cal-icon">
                                            <DatePicker
                                                selected={date}
                                                onChange={handleChange}
                                                className="form-control datetimepicker"
                                            />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div className="row">
                            <div className="col-sm-12">
                                <div className="card card-table"> 
                                    <div className="card-body">
                                        <div className="table-responsive">
                                            <table className="table table-center table-hover datatable" id="expensestable">
                                                <thead className="thead-light">
                                                    <tr>
                                                        <th>Category</th>
                                                        <th>Customer</th>
                                                        <th>Expense Date</th>
                                                        <th>Notes</th>
                                                        <th>Amount</th>
                                                        <th>Status</th>
                                                        <th className="text-right">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                {expenses.map((item, index) => {
                                                    let status;
                                                    if(item.status === 'Approved') {
                                                        status = <span className="badge badge-pill bg-success-light">{item.status}</span>
                                                    } else {
                                                        status = <span className="badge badge-pill bg-danger-light">{item.status}</span>
                                                    } 
                                                    return (
                                                    <tr key={index}>
                                                        <td>{item.category}</td>
                                                        <td>
                                                            <h2 className="table-avatar">
                                                                <Link to="/profile"><img className="avatar avatar-sm me-2 avatar-img rounded-circle" src={item.customer_image} alt="User Image" />{item.customer_name}</Link>
                                                            </h2>
                                                        </td>
                                                        <td>{item.expense_date}</td>
                                                        <td>{item.notes}</td>
                                                        <td>{item.amount}</td>
                                                        <td>{status}</td>
                                                        <td className="text-right">
                                                            <Link to="/edit-expenses" className="btn btn-sm btn-white text-success me-2"><i className="far fa-edit me-1"></i> Edit</Link> 
                                                            <a href="#" className="btn btn-sm btn-white text-danger"><i className="far fa-trash-alt me-1"></i>Delete</a>
                                                        </td>
                                                    </tr>
                                                    );  })}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
export default Expenses;
