// public/theme/vuejs-files/template-rtl/src/components/Chat.vue
<template>
		<!-- Main Wrapper -->
        <div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<div class="row">
						<div class="col-sm-12">
							<div class="chat-window">
								<div class="chat-cont-left">
									<div class="chat-header">
										<span>Chats</span>
										<a href="javascript:void(0)" class="chat-compose">
											<i class="material-icons">control_point</i>
										</a>
									</div>
									<form class="chat-search">
										<div class="input-group">
											<div class="input-group-prepend">
												<i class="fas fa-search"></i>
											</div>
											<input type="text" class="form-control" placeholder="Search">
										</div>
									</form>
									<div class="chat-users-list">
										<div class="chat-scroll">
											<a href="javascript:void(0);" class="media d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-away">
														<img src="../assets/img/profiles/avatar-03.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Marie Canales</div>
														<div class="user-last-chat">Hey, How are you?</div>
													</div>
													<div>
														<div class="last-chat-time block">2 min</div>
														<div class="badge badge-success badge-pill">15</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat active d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-online">
														<img src="../assets/img/profiles/avatar-04.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Barbara Moore</div>
														<div class="user-last-chat">I'll call you later </div>
													</div>
													<div>
														<div class="last-chat-time block">8:01 PM</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-away">
														<img src="../assets/img/profiles/avatar-05.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Greg Lynch</div>
														<div class="user-last-chat">Give me a full explanation about our project</div>
													</div>
													<div>
														<div class="last-chat-time block">7:30 PM</div>
														<div class="badge badge-success badge-pill">3</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-online">
														<img src="../assets/img/profiles/avatar-06.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Karlene Chaidez</div>
														<div class="user-last-chat">That's very good UI design</div>
													</div>
													<div>
														<div class="last-chat-time block">6:59 PM</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-offline">
														<img src="../assets/img/profiles/avatar-07.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">John Blair</div>
														<div class="user-last-chat">Yesterday i completed the task</div>
													</div>
													<div>
														<div class="last-chat-time block">11:21 AM</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-online">
														<img src="../assets/img/profiles/avatar-08.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Russell Copeland</div>
														<div class="user-last-chat">What is the major functionality?</div>
													</div>
													<div>
														<div class="last-chat-time block">10:05 AM</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-away">
														<img src="../assets/img/profiles/avatar-09.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Leatha Bailey</div>
														<div class="user-last-chat">This has allowed me to showcase not only my technical skills</div>
													</div>
													<div>
														<div class="last-chat-time block">Yesterday</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-offline">
														<img src="../assets/img/profiles/avatar-10.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Joseph Collins</div>
														<div class="user-last-chat">Let's talk briefly in the evening. </div>
													</div>
													<div>
														<div class="last-chat-time block">Sunday</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-online">
														<img src="../assets/img/profiles/avatar-11.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Jennifer Floyd</div>
														<div class="user-last-chat">Do you have any collections? If so, what of?</div>
													</div>
													<div>
														<div class="last-chat-time block">Saturday</div>
													</div>
												</div>
											</a>
											<a href="javascript:void(0);" class="media read-chat d-flex">
												<div class="media-img-wrap">
													<div class="avatar avatar-away">
														<img src="../assets/img/profiles/avatar-12.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
												</div>
												<div class="media-body">
													<div>
														<div class="user-name">Alex Campbell</div>
														<div class="user-last-chat">Connect the two modules with in 1 day.</div>
													</div>
													<div>
														<div class="last-chat-time block">Friday</div>
													</div>
												</div>
											</a>
										</div>
									</div>
								</div>
								<div class="chat-cont-right">
									<div class="chat-header">
										<a id="back_user_list" href="javascript:void(0)" class="back-user-list">
											<i class="material-icons">chevron_left</i>
										</a>
										<div class="media d-flex">
											<div class="media-img-wrap">
												<div class="avatar avatar-online">
													<img src="../assets/img/profiles/avatar-02.jpg" alt="User Image" class="avatar-img rounded-circle">
												</div>
											</div>
											<div class="media-body">
												<div class="user-name">Brian Johnson</div>
												<div class="user-status">online</div>
											</div>
										</div>
										<div class="chat-options">
											<a href="javascript:void(0)">
												<i class="material-icons">local_phone</i>
											</a>
											<a href="javascript:void(0)">
												<i class="material-icons">videocam</i>
											</a>
											<a href="javascript:void(0)">
												<i class="material-icons">more_vert</i>
											</a>
										</div>
									</div>
									<div class="chat-body">
										<div class="chat-scroll">
											<ul class="list-unstyled">
												<li class="media sent">
													<div class="media-body">
														<div class="msg-box">
															<div>
																<p>Hello. What can I do for you?</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:30 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
													</div>
												</li>
												<li class="media d-flex received">
													<div class="avatar">
														<img src="../assets/img/profiles/avatar-02.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
													<div class="media-body">
														<div class="msg-box">
															<div>
																<p>I'm just looking around.</p>
																<p>Will you tell me something about yourself?</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:35 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
														<div class="msg-box">
															<div>
																<p>Are you there? That time!</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:40 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
														<div class="msg-box">
															<div>
																<div class="chat-msg-attachments">
																	<div class="chat-attachment">
																		<img src="../assets/img/img-01.jpg" alt="">
																		<div class="chat-attach-caption">placeholder.jpg</div>
																		<a href="" class="chat-attach-download">
																			<i class="fas fa-download"></i>
																		</a>
																	</div>
																	<div class="chat-attachment">
																		<img src="../assets/img/img-01.jpg" alt="">
																		<div class="chat-attach-caption">placeholder.jpg</div>
																		<a href="" class="chat-attach-download">
																			<i class="fas fa-download"></i>
																		</a>
																	</div>
																</div>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:41 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
													</div>
												</li>
												<li class="media sent">
													<div class="media-body">
														<div class="msg-box">
															<div>
																<p>Where?</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:42 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
														<div class="msg-box">
															<div>
																<p>OK, my name is Limingqiang. I like singing, playing basketballand so on.</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:42 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
														<div class="msg-box">
															<div>
																<div class="chat-msg-attachments">
																	<div class="chat-attachment">
																		<img src="../assets/img/img-01.jpg" alt="">
																		<div class="chat-attach-caption">placeholder.jpg</div>
																		<a href="" class="chat-attach-download">
																			<i class="fas fa-download"></i>
																		</a>
																	</div>
																</div>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:50 AM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
													</div>
												</li>
												<li class="media d-flex received">
													<div class="avatar">
														<img src="../assets/img/profiles/avatar-02.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
													<div class="media-body">
														<div class="msg-box">
															<div>
																<p>You wait for notice.</p>
																<p>Consectetuorem ipsum dolor sit?</p>
																<p>Ok?</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>8:55 PM</span>
																		</div>
																	</li>
																</ul>
															</div>
														</div>
													</div>
												</li>
												<li class="chat-date">Today</li>
												<li class="media d-flex received">
													<div class="avatar">
														<img src="../assets/img/profiles/avatar-02.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
													<div class="media-body">
														<div class="msg-box">
															<div>
																<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,</p>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>10:17 AM</span>
																		</div>
																	</li>
																	<li><a href="#">Edit</a></li>
																</ul>
															</div>
														</div>
													</div>
												</li>
												<li class="media sent">
													<div class="media-body">
														<div class="msg-box">
															<div>
																<p>Lorem ipsum dollar sit</p>
																<div class="chat-msg-actions dropdown">
																	<a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
																		<i class="fe fe-elipsis-v"></i>
																	</a>
																	<div class="dropdown-menu dropdown-menu-right">
																		<a class="dropdown-item" href="#">Delete</a>
																	</div>
																</div>
																<ul class="chat-msg-info">
																	<li>
																		<div class="chat-time">
																			<span>10:19 AM</span>
																		</div>
																	</li>
																	<li><a href="#">Edit</a></li>
																</ul>
															</div>
														</div>
													</div>
												</li>
												<li class="media d-flex received">
													<div class="avatar">
														<img src="../assets/img/profiles/avatar-02.jpg" alt="User Image" class="avatar-img rounded-circle">
													</div>
													<div class="media-body">
														<div class="msg-box">
															<div>
																<div class="msg-typing">
																	<span></span>
																	<span></span>
																	<span></span>
																</div>
															</div>
														</div>
													</div>
												</li>
											</ul>
										</div>
									</div>
									<div class="chat-footer">
										<div class="input-group">
											<div class="input-group-prepend">
												<div class="btn-file btn">
													<i class="fas fa-paperclip"></i>
													<input type="file">
												</div>
											</div>
											<input type="text" class="input-msg-send form-control" placeholder="Type something">
											<div class="input-group-append">
												<button type="button" class="btn msg-send-btn"><i class="fas fa-paper-plane"></i></button>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Row -->
					
				</div>			
			</div>
			<!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->
</template>
<script>
export default {
	mounted() {
	var chatAppTarget = $('.chat-window');
	(function() {
		if ($(window).width() > 991)
			chatAppTarget.removeClass('chat-slide');
		
		$(document).on("click",".chat-window .chat-users-list a.media",function () {
			if ($(window).width() <= 991) {
				chatAppTarget.addClass('chat-slide');
			}
			return false;
		});
		$(document).on("click","#back_user_list",function () {
			if ($(window).width() <= 991) {
				chatAppTarget.removeClass('chat-slide');
			}	
			return false;
		});
	})();
	}

}
</script>

// public/theme/reactjs-files/template-rtl/src/application/Chat.jsx
import React from 'react';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import img1 from '../assets/img/img-01.jpg';
import img2 from '../assets/img/profiles/avatar-02.jpg';
import img3 from '../assets/img/profiles/avatar-03.jpg';
import img4 from '../assets/img/profiles/avatar-04.jpg';
import img5 from '../assets/img/profiles/avatar-05.jpg';
import img6 from '../assets/img/profiles/avatar-06.jpg';
import img7 from '../assets/img/profiles/avatar-07.jpg';
import img8 from '../assets/img/profiles/avatar-08.jpg';
import img9 from '../assets/img/profiles/avatar-09.jpg';
import img10 from '../assets/img/profiles/avatar-10.jpg';
import img11 from '../assets/img/profiles/avatar-11.jpg';
import img12 from '../assets/img/profiles/avatar-12.jpg';


const Chat = (props) => {
        return (

            <div className="main-wrapper">
                <Header />
                <Sidebar />
                
                <>
  {/* Page Wrapper */}
  <div className="page-wrapper">
    <div className="content container-fluid">
      <div className="row">
        <div className="col-sm-12">
          <div className="chat-window">
            <div className="chat-cont-left">
              <div className="chat-header">
                <span>Chats</span>
                <a href="javascript:void(0)" className="chat-compose">
                  <i className="material-icons">control_point</i>
                </a>
              </div>
              <form className="chat-search">
                <div className="input-group">
                  <div className="input-group-prepend">
                    <i className="fas fa-search" />
                  </div>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Search"
                  />
                </div>
              </form>
              <div className="chat-users-list">
                <div className="chat-scroll">
                  <a href="javascript:void(0);" className="media d-flex">
                    <div className="media-img-wrap">
                      <div className="avatar avatar-away">
                        <img
                          src={img3}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Marie Canales</div>
                        <div className="user-last-chat">Hey, How are you?</div>
                      </div>
                      <div>
                        <div className="last-chat-time block">2 min</div>
                        <div className="badge badge-success badge-pill">15</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat active d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-online">
                        <img
                          src={img4}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Barbara Moore</div>
                        <div className="user-last-chat">
                          I'll call you later{" "}
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">8:01 PM</div>
                      </div>
                    </div>
                  </a>
                  <a href="javascript:void(0);" className="media d-flex">
                    <div className="media-img-wrap">
                      <div className="avatar avatar-away">
                        <img
                          src={img5}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Greg Lynch</div>
                        <div className="user-last-chat">
                          Give me a full explanation about our project
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">7:30 PM</div>
                        <div className="badge badge-success badge-pill">3</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-online">
                        <img
                          src={img6}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Karlene Chaidez</div>
                        <div className="user-last-chat">
                          That's very good UI design
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">6:59 PM</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-offline">
                        <img
                          src={img7}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">John Blair</div>
                        <div className="user-last-chat">
                          Yesterday i completed the task
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">11:21 AM</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-online">
                        <img
                          src={img8}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Russell Copeland</div>
                        <div className="user-last-chat">
                          What is the major functionality?
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">10:05 AM</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-away">
                        <img
                          src={img9}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Leatha Bailey</div>
                        <div className="user-last-chat">
                          This has allowed me to showcase not only my technical
                          skills
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">Yesterday</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-offline">
                        <img
                          src={img10}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Joseph Collins</div>
                        <div className="user-last-chat">
                          Let's talk briefly in the evening.{" "}
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">Sunday</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-online">
                        <img
                          src={img11}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Jennifer Floyd</div>
                        <div className="user-last-chat">
                          Do you have any collections? If so, what of?
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">Saturday</div>
                      </div>
                    </div>
                  </a>
                  <a
                    href="javascript:void(0);"
                    className="media read-chat d-flex"
                  >
                    <div className="media-img-wrap">
                      <div className="avatar avatar-away">
                        <img
                          src={img12}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                    </div>
                    <div className="media-body">
                      <div>
                        <div className="user-name">Alex Campbell</div>
                        <div className="user-last-chat">
                          Connect the two modules with in 1 day.
                        </div>
                      </div>
                      <div>
                        <div className="last-chat-time block">Friday</div>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            </div>
            <div className="chat-cont-right">
              <div className="chat-header">
                <a
                  id="back_user_list"
                  href="javascript:void(0)"
                  className="back-user-list"
                >
                  <i className="material-icons">chevron_left</i>
                </a>
                <div className="media d-flex">
                  <div className="media-img-wrap">
                    <div className="avatar avatar-online">
                      <img
                        src={img2}
                        alt="User Image"
                        className="avatar-img rounded-circle"
                      />
                    </div>
                  </div>
                  <div className="media-body">
                    <div className="user-name">Brian Johnson</div>
                    <div className="user-status">online</div>
                  </div>
                </div>
                <div className="chat-options">
                  <a href="javascript:void(0)">
                    <i className="material-icons">local_phone</i>
                  </a>
                  <a href="javascript:void(0)">
                    <i className="material-icons">videocam</i>
                  </a>
                  <a href="javascript:void(0)">
                    <i className="material-icons">more_vert</i>
                  </a>
                </div>
              </div>
              <div className="chat-body">
                <div className="chat-scroll">
                  <ul className="list-unstyled">
                    <li className="media sent">
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <p>Hello. What can I do for you?</p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:30 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="media d-flex received">
                      <div className="avatar">
                        <img
                          src={img2}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <p>I'm just looking around.</p>
                            <p>Will you tell me something about yourself?</p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:35 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="msg-box">
                          <div>
                            <p>Are you there? That time!</p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:40 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="msg-box">
                          <div>
                            <div className="chat-msg-attachments">
                              <div className="chat-attachment">
                                <img src={img1} alt />
                                <div className="chat-attach-caption">
                                  placeholder.jpg
                                </div>
                                <a href className="chat-attach-download">
                                  <i className="fas fa-download" />
                                </a>
                              </div>
                              <div className="chat-attachment">
                                <img src={img1} alt />
                                <div className="chat-attach-caption">
                                  placeholder.jpg
                                </div>
                                <a href className="chat-attach-download">
                                  <i className="fas fa-download" />
                                </a>
                              </div>
                            </div>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:41 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="media sent">
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <p>Where?</p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:42 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="msg-box">
                          <div>
                            <p>
                              OK, my name is Limingqiang. I like singing,
                              playing basketballand so on.
                            </p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:42 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="msg-box">
                          <div>
                            <div className="chat-msg-attachments">
                              <div className="chat-attachment">
                                <img src={img1} alt />
                                <div className="chat-attach-caption">
                                  placeholder.jpg
                                </div>
                                <a href className="chat-attach-download">
                                  <i className="fas fa-download" />
                                </a>
                              </div>
                            </div>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:50 AM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="media d-flex received">
                      <div className="avatar">
                        <img
                          src={img2}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <p>You wait for notice.</p>
                            <p>Consectetuorem ipsum dolor sit?</p>
                            <p>Ok?</p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>8:55 PM</span>
                                </div>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="chat-date">Today</li>
                    <li className="media d-flex received">
                      <div className="avatar">
                        <img
                          src={img2}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <p>
                              Lorem ipsum dolor sit amet, consectetur adipiscing
                              elit,
                            </p>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>10:17 AM</span>
                                </div>
                              </li>
                              <li>
                                <a href="#">Edit</a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="media sent">
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <p>Lorem ipsum dollar sit</p>
                            <div className="chat-msg-actions dropdown">
                              <a
                                href="#"
                                data-bs-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false"
                              >
                                <i className="fe fe-elipsis-v" />
                              </a>
                              <div className="dropdown-menu dropdown-menu-right">
                                <a className="dropdown-item" href="#">
                                  Delete
                                </a>
                              </div>
                            </div>
                            <ul className="chat-msg-info">
                              <li>
                                <div className="chat-time">
                                  <span>10:19 AM</span>
                                </div>
                              </li>
                              <li>
                                <a href="#">Edit</a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="media d-flex received">
                      <div className="avatar">
                        <img
                          src={img2}
                          alt="User Image"
                          className="avatar-img rounded-circle"
                        />
                      </div>
                      <div className="media-body">
                        <div className="msg-box">
                          <div>
                            <div className="msg-typing">
                              <span />
                              <span />
                              <span />
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="chat-footer">
                <div className="input-group">
                  <div className="input-group-prepend">
                    <div className="btn-file btn">
                      <i className="fas fa-paperclip" />
                      <input type="file" />
                    </div>
                  </div>
                  <input
                    type="text"
                    className="input-msg-send form-control"
                    placeholder="Type something"
                  />
                  <div className="input-group-append">
                    <button type="button" className="btn msg-send-btn">
                      <i className="fas fa-paper-plane" />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Row */}
    </div>
  </div>
  {/* /Page Wrapper */}
</>
            
            </div>
        );
    
}
export default Chat;
