// public/theme/reactjs-files/template-rtl/src/payments/Index.jsx
import React, {useState, useEffect} from 'react'
import { Link } from 'react-router-dom'
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import payments from '../json/payments'
import datatable from '../utils/utils'
import Select2 from 'react-select2-wrapper';
import DatePicker from 'react-datepicker';

const Payments = () => {
    
	const [date, setDate] = useState(new Date());
	const [options, setOptions] = useState([
		{ id: 1, text: 'Draft' },
		{ id: 2, text: 'Sent' },
		{ id: 3, text: 'Viewed' },
		{ id: 4, text: 'Expired' },
		{ id: 5, text: 'Accepted' },
		{ id: 6, text: 'Rejected' },
	]);

	useEffect(() => {
		datatable('#paymentstable')
		$("#filter_search").click(function(){
			$("#filter_inputs").slideToggle(500);
        });
        let elements = Array.from(document.getElementsByClassName('select2-container'));
        elements.map(element => element.classList.add("width-100"))
	},[]);

	return (

		<div className="main-wrapper">
            <Header />
			<Sidebar />
			
			<div className="page-wrapper">
				<div className="content container-fluid">
			
					<div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Payments</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link></li>
									<li className="breadcrumb-item active">Payments</li>
								</ul>
							</div>
							<div className="col-auto">
								<Link to="/add-payments"  className="btn btn-primary me-1">
									<i className="fas fa-plus"></i>
								</Link>
								<a className="btn btn-primary filter-btn" href="/payments#" id="filter_search">
									<i className="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					
					<div id="filter_inputs" className="card filter-card">
						<div className="card-body pb-0">
							<div className="row">
								<div className="col-sm-6 col-md-3">
									<div className="form-group">
										<label>Customer</label>
										<input type="text" className="form-control" />
									</div>
								</div>
								<div className="col-sm-6 col-md-3">
									<div className="form-group">
										<label>Price</label>
										<input type="text" className="form-control" />
									</div>
								</div>
								<div className="col-sm-6 col-md-3">
									<div className="form-group">
										<label>Payment Mode</label>
										<Select2
                                            className="w-100"
                                            data={options}
                                            options={{
                                                placeholder: 'Select Status',
                                            }}
                                        />
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div className="row">
						<div className="col-sm-12">
							<div className="card card-table">
								<div className="card-body">
									<div className="table-responsive">
										<table className="table table-center table-hover datatable" id="paymentstable">
											<thead className="thead-light">
												<tr>
													<th>Reference ID</th>
													<th>Customer</th>
													<th>Amount</th>
													<th>Date</th>
													<th>Payment Method</th>
													<th className="text-right">Action</th>
												</tr>
											</thead>
											<tbody>
                                            {payments.map((item, index) => {
                                                return (
												<tr key={index}>
													<td><a href="#">{item.reference_id}</a></td>
													<td>
														<h2 className="table-avatar">
															<Link to="/profile"><img className="avatar avatar-sm me-2 avatar-img rounded-circle" src={item.customer_image} alt="User Image" />{item.customer_name}</Link>
														</h2>
													</td>
													<td>{item.amount}</td>
													<td>{item.date}</td>
													<td>{item.payment_card}<strong>{item.card_no}</strong></td>
													<td className="text-right">
														<a className="btn btn-sm btn-white me-2" href="#">
															<i className="fas fa-download me-1"></i> PDF
														</a>
														<Link className="btn btn-sm btn-white" to="/view-invoice">
															<i className="far fa-eye me-1"></i> View
														</Link>
													</td>
												</tr>
                                                );  })}
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
        );
}
export default Payments;

// public/theme/vuejs-files/template-rtl/src/components/Payments.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
			
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Payments</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link></li>
									<li class="breadcrumb-item active">Payments</li>
								</ul>
							</div>
							<div class="col-auto">
								<router-link to="/add-payment"  class="btn btn-primary me-2">
									<i class="fas fa-plus"></i>
								</router-link>
								<a class="btn btn-primary filter-btn" href="javascript:void(0);" @click="toggleContent" id="filter_search">
									<i class="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<!-- Search Filter -->
					<div id="filter_inputs" class="card filter-card">
						<div class="card-body pb-0">
							<div class="row">
								<div class="col-sm-6 col-md-3">
									<div class="form-group">
										<label>Customer</label>
										<input type="text" class="form-control">
									</div>
								</div>
								<div class="col-sm-6 col-md-3">
									<div class="form-group">
										<label>Price</label>
										<input type="text" class="form-control">
									</div>
								</div>
								<div class="col-sm-6 col-md-3">
									<div class="form-group">
										<label>Payment Mode</label>
										<select class="select">
											<option>Payment Mode</option>
											<option>Cash</option>
											<option>Cheque</option>
											<option>Card</option>
											<option>Online</option>
										</select>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-sm-12">
							<div class="card card-table">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center table-hover datatable" id="paymentTable">
											<thead class="thead-light">
												<tr>
													<th>Reference ID</th>
													<th>Customer</th>
													<th>Amount</th>
													<th>Date</th>
													<th>Payment Method</th>
													<th class="text-right">Action</th>
												</tr>
											</thead>
											<tbody>
												<tr v-for="item in payments" :key="item.id">
													<td><a href="javascript:void(0);">{{item.reference_id}}</a></td>
													<td>
														<h2 class="table-avatar">
															<router-link to="/customer/profile"><img class="avatar avatar-sm me-2 avatar-img rounded-circle" :src="loadImg(item.customer_image)" alt="User Image"> {{item.customer_name}}</router-link>
														</h2>
													</td>
													<td>{{item.amount}}</td>
													<td>{{item.date}}</td>
													<td>{{item.payment_card}} <strong>{{item.card_no}}</strong></td>
													<td class="text-right">
														<a class="btn btn-sm btn-white me-2" href="javascript:void(0);">
															<i class="fas fa-download me-1"></i> PDF
														</a>
														<router-link class="btn btn-sm btn-white ms-1" to="/view-invoice">
															<i class="far fa-eye me-1"></i> View
														</router-link>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
			
		</div>
		<!-- /Main Wrapper -->
</template>
<script>
import payments from '../assets/json/payments.json';
const images = require.context('../assets/img/profiles', false, /\.png$|\.jpg$/)
export default {
	data() {
		return {
			payments: payments
		}
	},
	mounted() {
		if ($('.datatable').length > 0) {
		$('.datatable').DataTable({
			"bFilter": false,
		});
	}
        
        if ($('.select').length > 0) {
            $('.select').select2({
                minimumResultsForSearch: -1,
                width: '100%'
            });
        }
		$(document).on('click', '#filter_search', function() {
			$('#filter_inputs').slideToggle("slow");
		});
	},
	methods: {
        loadImg(imgPath) {
            return images('./' + imgPath).default
        },
        
    },
}
</script>
