// public/theme/reactjs-files/template-rtl/src/reports/salesreport.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom';
import Select2 from 'react-select2-wrapper';
import reports from '../json/report';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import $ from 'jquery'
const SlideToggle = window.ReactSlideToggle

const SalesReport = () => {
	const [date_range_, setdaterange] = useState( [
            { id:2, text: 'Today' },
            { id:3, text: 'This Week' },
            { id:4, text: 'This Month' },
			{ id:5, text: 'This Quarter'},
            { id:6, text: 'This Year' },
            { id:7, text: 'Previous Week' },
            { id:8, text: 'Previous Month' },
			{ id:9, text: 'Previous Quarter'},
			{ id:10, text: 'Previous Year'}
		]);

	useEffect(() => {
        $('#salesreporttable').DataTable({
			"bFilter": false,
			"paging": true,
		});
		$("#filter_search").click(function(){
			$("#filter_inputs").slideToggle(500);
		});
	},[]);
	
    return (
		<div className="main-wrapper">
		
			<Header />
			<Sidebar />
			
			<div className="page-wrapper">
				<div className="content container-fluid">
				
					<div className="page-header">
						<div className="row align-items-center">
							<div className="col">
								<h3 className="page-title">Sales Report</h3>
								<ul className="breadcrumb">
									<li className="breadcrumb-item"><Link to="/index">Dashboard</Link>
									</li>
									<li className="breadcrumb-item active">Reports</li>
								</ul>
							</div>
							<div className="col-auto">
								<a href="#" className="btn btn-primary me-1">
								<i className="fas fa-file-pdf" />
								</a>
								<a
								className="btn btn-primary filter-btn"
								href="/expenses-report#"
								id="filter_search"
								>
								<i className="fas fa-filter" />
								</a>
							</div>
						</div>
					</div>
                    {/* Search Filter */}
                    <div id="filter_inputs" className="card filter-card">
                        <div className="card-body pb-0">
                        <div className="row">
                            <div className="col-md-3">
                            <div className="form-group">
                                <label>Slect Date Range</label><br/>
                                <Select2 style={{ innerWidth : "250px" }}
                                    className="w-100"
                                    data={date_range_}
                                    options={{
                                        placeholder: 'Select',
                                    }}
                                />                                
                            </div>
                            </div>
                            <div className="col-md-3">
                            <div className="form-group">
                                <label>From</label>
                                <div className="">
                                <input className="form-control datetimepicker" type="date" />
                                </div>
                            </div>
                            </div>
                            <div className="col-md-3">
                            <div className="form-group">
                                <label>To</label>
                                <div className="">
                                <input className="form-control datetimepicker" type="date" />
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    {/* /Search Filter */}
					
					<div className="row">
						<div className="col-sm-12">
							<div className="card card-table">
								<div className="card-body">
									<div className="table-responsive">
										<table className="table table-center table-hover datatable" id="salesreporttable">
											<thead className="thead-light">
												<tr>
													<th>#</th>
													<th>Date</th>
													<th>Category</th>
													<th>Sales</th>
													<th>Refunded</th>
													<th>Discounts</th>
													<th>Taxs</th>
													<th>Amount</th>
												</tr>
											</thead>
											<tbody>
											{reports.map((item, index) => {
												return (
												<tr key={index}>
													<td>{item.id}</td>
													<td>{item.date}</td>
													<td>{item.category}</td>
													<td>{item.sales}</td>
													<td>{item.refunded}</td>
													<td>{item.discounts}</td>
													<td>{item.taxr}</td>
													<td>{item.amount}</td>
												</tr>
											 );  })}
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
        );
}
export default SalesReport;

// public/theme/vuejs-files/template-rtl/src/components/Salesreport.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
			<layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Sales Report</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link></li>
									<li class="breadcrumb-item active">Reports</li>
								</ul>
							</div>
							<div class="col-auto">
								<a href="#"  class="btn btn-primary me-1">
									<i class="fas fa-file-pdf"></i>
								</a>
								<a class="btn btn-primary filter-btn" href="javascript:void(0);" @click="toggleContent" id="filter_search">
									<i class="fas fa-filter"></i>
								</a>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
			   
					<!-- Search Filter -->
					<div id="filter_inputs" class="card filter-card">
						<div class="card-body pb-0">
							<div class="row">
								<div class="col-md-4">
									<div class="form-group">
										<label>Slect Date Range</label>
										<select class="select">
											<option>Select</option>
											<option>Today</option>
											<option>This Week</option>
											<option>This Month</option>
											<option>This Quarter</option>
											<option>This Year</option>
											<option>Previous Week</option>
											<option>Previous Month</option>
											<option>Previous Quarter</option>
											<option>Previous Year</option>
										</select>
									</div>
								</div>
								
								<div class="col-md-4">
									<div class="form-group">
										<label>From</label>
										<div class="cal-icon">
											<input class="form-control datetimepicker" type="text">
										</div>
									</div>
								</div>
								<div class="col-md-4">
									<div class="form-group">
										<label>To</label>
										<div class="cal-icon">
											<input class="form-control datetimepicker" type="text">
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /Search Filter -->
					
					<div class="row">
						<div class="col-sm-12">
							<div class="card card-table"> 
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-center table-hover datatable" id="customerTable">
											<thead class="thead-light">
												<tr>
													<th>#</th>
													<th>Date</th>
													<th>Category</th>
													<th>Sales</th>
													<th>Refunded</th>
													<th>Discounts</th>
													<th>Taxs</th>
													<th>Amount</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>1</td>
													<td>7 Jan 2021</td>
													<td>Accessories</td>
													<td>$42</td>
													<td>$0</td>
													<td>$163</td>
													<td>$221</td>
													<td>$762</td>
												</tr>
												<tr>
													<td>2</td>
													<td>28 Feb 2021</td>
													<td>Books</td>
													<td>$1249</td>
													<td>$36</td>
													<td>$3</td>
													<td>$80</td>
													<td>$1238</td>
												</tr>
												<tr>
													<td>3</td>
													<td>10 Mar 2021</td>
													<td>Others</td>
													<td>$76</td>
													<td>$0</td>
													<td>$0</td>
													<td>$4</td>
													<td>$80</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
					
				</div>			
			</div>
			<!-- /Page Wrapper -->
			
		</div>
		<!-- /Main Wrapper -->
</template>
<script>
import customers from '../assets/json/customers.json';
const images = require.context('../assets/img/profiles', false, /\.png$|\.jpg$/)
export default {
	data() {
		return {
			customers: customers
		}
	},
	mounted() {
		// Select 2
	if ($('.select').length > 0) {
		$('.select').select2({
			minimumResultsForSearch: -1,
			width: '100%'
		});
	}
	// Datetimepicker
	if($('.datetimepicker').length > 0 ){
		$('.datetimepicker').datetimepicker({
			format: 'DD-MM-YYYY',
			icons: {
				up: "fas fa-angle-up",
				down: "fas fa-angle-down",
				next: 'fas fa-angle-right',
				previous: 'fas fa-angle-left'
			}
		});
	}
	if ($('.datatable').length > 0) {
		$('.datatable').DataTable({
			"bFilter": false,
		});
	}
	$(document).on('click', '#filter_search', function() {
			$('#filter_inputs').slideToggle("slow");
		});
	
	},
	methods: {
        loadImg(imgPath) {
            return images('./' + imgPath).default
		}
        
    },
}
</script>
