// public/theme/reactjs-files/template-rtl/src/users/Index.jsx
import React, {useEffect} from 'react';
import { Link } from 'react-router-dom';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'
import $ from 'jquery'
import users from '../json/users'

const Users = () => {

    useEffect(() => {
		$('#userstable').DataTable({
			"bFilter": false,
			"paging": true,
		});
		$("#filter_search").click(function(){
			$("#filter_inputs").slideToggle(500);
		});
	},[]);
		
        return (
	
            <div className="main-wrapper">
            
                <Header />
                <Sidebar />
                
                {/* Page wrapper */}
                <div className="page-wrapper">
                    <div className="content container-fluid">
                    
                        <div className="page-header">
                            <div className="row align-items-center">
                                <div className="col">
                                    <h3 className="page-title">Users</h3>
                                    <ul className="breadcrumb">
                                        <li className="breadcrumb-item"><Link to="/index">Dashboard</Link></li>
                                        <li className="breadcrumb-item active">Users</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    
                        <div className="row">
                            <div className="col-sm-12">
                            
                                <div className="card card-table">
                                    <div className="card-header">
                                        <h4 className="card-title">List of Users</h4>
                                    </div>
                                    <div className="card-body">
                                        <div className="table-responsive">
                                            <table className="table table-stripped table-center table-hover datatable" id="userstable">
                                                <thead className="thead-light">
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Email</th>
                                                        <th>Registered On</th>
                                                        <th>Role</th>
                                                        <th>Status</th>
                                                        <th className="text-right">Actions</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                {users.map((item, index) => {
                                                    let status;
                                                    let role;
                                                    if(item.status === 'Active') {
                                                        status = <span className="badge badge-pill bg-success-light">Active</span>
                                                    } else {
                                                        status = <span className="badge badge-pill bg-danger-light">Inactive</span>
                                                    }
                                                    
                                                    if(item.role === 'Admin') {
                                                        
                                                        role = <span className="text-success">Admin</span>
                                                    } else {
                                                        role = <span className="text-info">Customer</span>
                                                    }
                                                    return (
                                                    <tr key={index}>
                                                        <td>
                                                            <h2 className="table-avatar">
                                                                <Link to="/profile"><img className="avatar avatar-sm me-2 avatar-img rounded-circle" src={item.customer_image} alt="User Image" /> {item.customer_name}</Link>
                                                            </h2>
                                                        </td>
                                                        <td>{item.email}</td>
                                                        <td>{item.registered_on}</td>
                                                        <td>{role}</td>
                                                        <td>{status}</td>
                                                        <td className="text-right">
                                                            <a href="#" className="btn btn-sm btn-white text-success me-2"><i className="far fa-edit me-1"></i> Edit</a> 
                                                            <a href="#" className="btn btn-sm btn-white text-danger me-2"><i className="far fa-trash-alt me-1"></i>Delete</a>
                                                        </td>
                                                    </tr>
                                                  );  })}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>					
                        </div>					
                    </div>			
                </div>
                
            </div>
            
        );
    
}
export default Users;

// public/theme/vuejs-files/template-rtl/src/components/Users.vue
<template>
    <!-- Main Wrapper -->
		<div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Users</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link></li>
									<li class="breadcrumb-item active">Users</li>
								</ul>
							</div>
						</div>
					</div>
				
					<div class="row">
						<div class="col-sm-12">
						
							<div class="card card-table">
								<div class="card-header">
									<h4 class="card-title">List of Users</h4>
								</div>
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-stripped table-center table-hover datatable" id="usersTable">
											<thead class="thead-light">
												<tr>
													<th>Name</th>
													<th>Email</th>
													<th>Registered On</th>
													<th>Role</th>
													<th>Status</th>
													<th class="text-end">Actions</th>
												</tr>
											</thead>
											<tbody>
												<tr v-for="item in users" :key="item.id">
													<td>
														<h2 class="table-avatar">
															<router-link to="/customer/profile"><img class="avatar avatar-sm me-2 avatar-img rounded-circle" :src="loadImg(item.customer_image)" alt="User Image"> {{item.customer_name}}</router-link>
														</h2>
													</td>
													<td>{{item.email}}</td>
													<td>{{item.registered_on}}</td>
													<td><span class="text-success" v-if="item.role == 'Admin'">Admin</span>
                                                        <span class="text-info" v-if="item.role == 'Customer'">Customer</span>
                                                       </td>
													<td>
													<span class="badge badge-pill bg-success-light" v-if="item.status == 'Active'">Active</span>
                                                        <span class="badge badge-pill bg-danger-light" v-if="item.status == 'Inactive'">Inactive</span>
													</td>
													<td class="text-end">
														<a href="javascript:void(0);" class="btn btn-sm btn-white text-success me-2"><i class="far fa-edit me-1"></i> Edit</a> 
														<a href="javascript:void(0);" class="btn btn-sm btn-white text-danger me-2"><i class="far fa-trash-alt me-1"></i>Delete</a>
													</td>
												</tr>
											</tbody>
										</table>
									</div>
								</div>
							</div>
							
						</div>					
					</div>					
				</div>			
			</div>
			<!-- /Page Wrapper -->
			
        </div>
		<!-- /Main Wrapper -->
</template>

<script>
import users from '../assets/json/users.json';
const images = require.context('../assets/img/profiles', false, /\.png$|\.jpg$/)
export default {
	data() {
		return {
			users: users
		}
	},
	mounted() {
       
       if ($('.datatable').length > 0) {
		$('.datatable').DataTable({
			"bFilter": false,
		});
	}

		$(document).on('click', '#filter_search', function() {
			$('#filter_inputs').slideToggle("slow");
		});
	},
	methods: {
        loadImg(imgPath) {
            return images('./' + imgPath).default
        },
        
    },
}
</script>
