// public/theme/vuejs-files/template-rtl/src/components/FormInputGroups.vue
<template>
    <!-- Main Wrapper -->
        <div class="main-wrapper">
            <layout-header></layout-header>
			<layout-sidebar></layout-sidebar>
			
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
					
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col">
								<h3 class="page-title">Input Groups</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/">Dashboard</router-link></li>
									<li class="breadcrumb-item active">Input Groups</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<div class="row">
						<div class="col-lg-12">
							<div class="card">
								<div class="card-header">
									<h5 class="card-title">Basic Examples</h5>
								</div>
								<div class="card-body">
									<form action="#">
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Group Left</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text" id="basic-addon1">@</span>
													<input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
												</div>
											</div>
										</div>
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Group Right</label>
											<div class="col-lg-10">
												<div class="input-group">
													<input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
													<span class="input-group-text" id="basic-addon2">@example.com</span>
												</div>
											</div>
										</div>
										<div class="form-group row">
											<label class="col-form-label col-lg-2">URL Example</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text" id="basic-addon3">https://example.com/users/</span>
													<input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3">
												</div>
											</div>
										</div>

										<div class="form-group row">
											<label class="col-form-label col-lg-2">Group with Price</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text">$</span>
													<input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
													<span class="input-group-text">.00</span>
												</div>
											</div>
										</div>

										<div class="form-group row mb-0">
											<label class="col-form-label col-lg-2">Group with Price (Left)</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text">$</span>
													<span class="input-group-text">0.00</span>
													<input type="text" class="form-control">
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="card">
								<div class="card-header">
									<h5 class="card-title">Sizing</h5>
								</div>
								<div class="card-body">
									<form action="#">
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Input Group Large</label>
											<div class="col-lg-10">
												<div class="input-group input-group-lg">
													<span class="input-group-text" id="inputGroup-sizing-lg">Large</span>
													<input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">
												</div>
											</div>
										</div>
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Input Group Default</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text" id="inputGroup-sizing-default">Default</span>
  													<input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
												</div>
											</div>
										</div>
										<div class="form-group row mb-0">
											<label class="col-form-label col-lg-2">Input Group Small</label>
											<div class="col-lg-10">
												<div class="input-group input-group-sm">
													<span class="input-group-text" id="inputGroup-sizing-sm">Small</span>
  													<input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="card">
								<div class="card-header">
									<h5 class="card-title">Checkbox and Radio Addons</h5>
								</div>
								<div class="card-body">
									<form action="#">
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Checkbox</label>
											<div class="col-lg-10">
												<div class="input-group">
													<div class="input-group-text">
														<input class="form-check-input" type="checkbox" value="" aria-label="Checkbox for following text input">
													</div>
													<input type="text" class="form-control" aria-label="Text input with checkbox">
												</div>
											</div>
										</div>
										<div class="form-group row mb-0">
											<label class="col-form-label col-lg-2">Radio</label>
											<div class="col-lg-10">
												<div class="input-group">
													<div class="input-group-text">
														<input class="form-check-input" type="radio" value="" aria-label="Radio button for following text input">
													</div>
													<input type="text" class="form-control" aria-label="Text input with radio button">
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="card">
								<div class="card-header">
									<h5 class="card-title">Multiple Addons</h5>
								</div>
								<div class="card-body">
									<form action="#">
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Radio and Text Addons</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text">
														<input type="checkbox">
													</span>
													<span class="input-group-text">$</span>
													<input type="text" class="form-control">
												</div>
											</div>
										</div>
										<div class="form-group row mb-0">
											<label class="col-form-label col-lg-2">Two Addons</label>
											<div class="col-lg-10">
												<div class="input-group">
													<span class="input-group-text">$</span>
													<span class="input-group-text">0.00</span>
													<input type="text" class="form-control">
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="card">
								<div class="card-header">
									<h5 class="card-title">Buttons with dropdowns</h5>
								</div>
								<div class="card-body">
									<form action="#">
										<div class="form-group row">
											<label class="col-form-label col-lg-2">Left Dropdown Text Addons</label>
											<div class="col-lg-10">
												<div class="input-group">
													<button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button>
													<ul class="dropdown-menu">
														<li><a class="dropdown-item" href="#">Action</a></li>
														<li><a class="dropdown-item" href="#">Another action</a></li>
														<li><a class="dropdown-item" href="#">Something else here</a></li>
														<li><hr class="dropdown-divider"></li>
														<li><a class="dropdown-item" href="#">Separated link</a></li>
													</ul>
													<input type="text" class="form-control" aria-label="Text input with dropdown button">
												</div>
											</div>
										</div>

										<div class="form-group row mb-0">
											<label class="col-form-label col-lg-2">Right Dropdown Text Addons</label>
											<div class="col-lg-10">
												<div class="input-group">
													<input type="text" class="form-control" aria-label="Text input with dropdown button">
													<button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</button>
													<ul class="dropdown-menu dropdown-menu-end">
														<li><a class="dropdown-item" href="#">Action</a></li>
														<li><a class="dropdown-item" href="#">Another action</a></li>
														<li><a class="dropdown-item" href="#">Something else here</a></li>
														<li><hr class="dropdown-divider"></li>
														<li><a class="dropdown-item" href="#">Separated link</a></li>
													</ul>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				
				</div>			
			</div>
			<!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->
</template>

// public/theme/reactjs-files/template-rtl/src/forms/FormInputGroups.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const FormInputGroups = () => {
        
        return (
        
            <div className="main-wrapper">
            
                <Header />
                <Sidebar />
                
               {/* Page wrapper */}
                <div className="page-wrapper">
                    <div className="content container-fluid">
                        
                        {/* Page Header */}
                        <div className="page-header">
                            <div className="row">
                                <div className="col">
                                    <h3 className="page-title">Input Groups</h3>
                                    <ul className="breadcrumb">
                                        <li className="breadcrumb-item"><Link to="/index">Dashboard</Link></li>
                                        <li className="breadcrumb-item active">Input Groups</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {/* /Page Header */}
                        
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="card">
                                    <div className="card-header">
                                        <h5 className="card-title">Basic Examples</h5>
                                    </div>
                                    <div className="card-body">
                                        <form action="#">
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Group Left</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text" id="basic-addon1">@</span>
                                                        </div>
                                                        <input type="text" className="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Group Right</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <input type="text" className="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2" />
                                                        <div className="input-group-append">
                                                            <span className="input-group-text" id="basic-addon2">@example.com</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">URL Example</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">https://</span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
    
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Group with Price</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">$</span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                        <div className="input-group-append">
                                                            <span className="input-group-text">.00</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
    
                                            <div className="form-group row mb-0">
                                                <label className="col-form-label col-lg-2">Group with Price (Left)</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">$</span>
                                                        </div>
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">0.00</span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div className="card">
                                    <div className="card-header">
                                        <h5 className="card-title">Sizing</h5>
                                    </div>
                                    <div className="card-body">
                                        <form action="#">
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Input Group Large</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group input-group-lg">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text" id="sizing-addon1">@</span>
                                                        </div>
                                                        <input type="text" className="form-control" placeholder="Username" aria-describedby="sizing-addon1" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Input Group Default</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text" id="sizing-addon2">@</span>
                                                        </div>
                                                        <input type="text" className="form-control" placeholder="Username" aria-describedby="sizing-addon2" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="form-group row mb-0">
                                                <label className="col-form-label col-lg-2">Input Group Small</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group input-group-sm">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text" id="sizing-addon3">@</span>
                                                        </div>
                                                        <input type="text" className="form-control" placeholder="Username" aria-describedby="sizing-addon3" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div className="card">
                                    <div className="card-header">
                                        <h5 className="card-title">Checkbox and Radio Addons</h5>
                                    </div>
                                    <div className="card-body">
                                        <form action="#">
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Checkbox</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">
                                                                <input type="checkbox" />
                                                            </span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="form-group row mb-0">
                                                <label className="col-form-label col-lg-2">Radio</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">
                                                                <input type="radio" />
                                                            </span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div className="card">
                                    <div className="card-header">
                                        <h5 className="card-title">Multiple Addons</h5>
                                    </div>
                                    <div className="card-body">
                                        <form action="#">
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Radio and Text Addons</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">
                                                                <input type="checkbox" />
                                                            </span>
                                                        </div>
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">$</span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="form-group row mb-0">
                                                <label className="col-form-label col-lg-2">Two Addons</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">$</span>
                                                        </div>
                                                        <div className="input-group-prepend">
                                                            <span className="input-group-text">0.00</span>
                                                        </div>
                                                        <input type="text" className="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div className="card">
                                    <div className="card-header">
                                        <h5 className="card-title">Buttons with dropdowns</h5>
                                    </div>
                                    <div className="card-body">
                                        <form action="#">
                                            <div className="form-group row">
                                                <label className="col-form-label col-lg-2">Radio and Text Addons</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <div className="input-group-prepend">
                                                            <button type="button" className="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">Action</button>
                                                            <div className="dropdown-menu">
                                                                <a className="dropdown-item" href="#">Action</a>
                                                                <a className="dropdown-item" href="#">Another action</a>
                                                                <a className="dropdown-item" href="#">Something else here</a>
                                                                <div role="separator" className="dropdown-divider"></div>
                                                                <a className="dropdown-item" href="#">Separated link</a>
                                                            </div>
                                                        </div>
                                                        <input type="text" className="form-control" placeholder="Left dropdown" />
                                                    </div>
                                                </div>
                                            </div>
    
                                            <div className="form-group row mb-0">
                                                <label className="col-form-label col-lg-2">Two Addons</label>
                                                <div className="col-lg-10">
                                                    <div className="input-group">
                                                        <input type="text" className="form-control" placeholder="Right dropdown" />
                                                        <div className="input-group-append">
                                                            <button type="button" className="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">Action</button>
                                                            <div className="dropdown-menu dropdown-menu-right">
                                                                <a className="dropdown-item" href="#">Action</a>
                                                                <a className="dropdown-item" href="#">Another action</a>
                                                                <a className="dropdown-item" href="#">Something else here</a>
                                                                <div role="separator" className="dropdown-divider"></div>
                                                                <a className="dropdown-item" href="#">Separated link</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    </div>			
                </div>
                {/* Page wrapper */}

                {/* Main wrapper */}
            </div>
        );
    
}
export default FormInputGroups;
